version: '3'

services:
    postgresql:
        restart: always
        image: mdillon/postgis:9.5-alpine
        volumes:
            - /srv/docker/tendenci/postgresql:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=tendenci
            - POSTGRES_USER=tendenci
            - POSTGRES_PASSWORD=password
            - PGDATA=/var/lib/postgresql/data/pgdata
        networks:
          - backend

    tendenci:
        restart: always
        build: .
        volumes:
            - /srv/docker/tendenci/app/logs:/var/log/tendenci
            - /srv/docker/tendenci/app/data:/home/tendenci/data
        depends_on:
            - postgresql
        expose:
            - 8000
        environment:
            # Postgresql setup
            - DB_USER=tendenci
            - DB_NAME=tendenci
            - DB_PASS=password
            - DB_HOST=postgresql
            - DB_PORT=5432

            # Superuser setup
            - ADMIN_USER=admin
            - ADMIN_MAIL=admin@example.com
            - ADMIN_PASS=password
        networks:
          backend:
            aliases:
              - postgresql

networks:
  backend:
